
services:
  web:
    image: node:lts
    privileged: false
    container_name: uol_container_web
    network_mode: host
    volumes:
      - ./web/Frontend:/Frontend:rw
      - ./web/SignallingWebServer:/SignallingWebServer:rw
    command: ["/SignallingWebServer/platform_scripts/bash/Start_SignallingServer.sh"] # not run_local.sh
  game:
    build:
      context: .
      dockerfile: Dockerfile
    image: uol_image/game
    network_mode: host
    privileged: false
    container_name: uol_container_game
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./Linux:/home/runtime/game:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ['/home/runtime/game/SplattingDemo.sh',
              '-PixelStreamingIP=0.0.0.0', '-PixelStreamingPort=8888',
              '-RenderOffScreen', '-nosound', '-vulkan', '-ResX=600', '-ResY=300']
