
services:
  web:
    build:
      context: ./web
      dockerfile: SignallingWebServer/Dockerfile
    image: uol_image/web
    privileged: false
    container_name: uol_container_web
    environment:
      - http_proxy=""
      - https_proxy=""
    networks:
      custom_network:
        ipv4_address: 192.168.1.100
    ports:
      - "80:80"
      - "443:443"
    command: ["/usr/local/bin/node",
              "/opt/SignallingWebServer/cirrus.js",
              "--PublicIp", "0.0.0.0",
              "--StreamerPort","8888"]
  game:
    build:
      context: .
      dockerfile: Dockerfile
    image: uol_image/game
    networks:
      custom_network:
        ipv4_address: 192.168.1.101
    ports:
      - "8888:8888"
    privileged: false
    container_name: uol_container_game
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro
      - ./Linux:/home/runtime/game:rw
    depends_on:
      - web
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ['/home/runtime/game/MyProject5.sh',
              '-PixelStreamingIP=192.168.1.100', '-PixelStreamingPort=8888',
              '-RenderOffScreen']

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
